### ISSUE TITLE
Can Not install websocketpp by homebrew (MacOS)

### ISSUE THREAD

**Issue by Brian0906** [geek-ai/MAgent#17]
briandeMacBook-Pro:MAgent brian$ brew install --HEAD david-icracked/websocketpp/websocketpp
==> Installing websocketpp from david-icracked/websocketpp
==> Cloning git://github.com/zaphoyd/websocketpp
Updating /Users/brian/Library/Caches/Homebrew/websocketpp--git
==> Checking out branch master
Error: Calling Formula#std_cmake_parameters is disabled!
Use Formula#std_cmake_args instead.
/usr/local/Homebrew/Library/Taps/david-icracked/homebrew-websocketpp/websocketpp.rb:9:in `install'
Please report this to the david-icracked/websocketpp tap!
Or, even better, submit a PR to fix it!

**Comment by rideoff** [comment]
==> Installing websocketpp from david-icracked/websocketpp
==> Cloning git://github.com/zaphoyd/websocketpp
Updating /Users/lanjiedediannao/Library/Caches/Homebrew/websocketpp--git
==> Checking out branch master
==> cmake  . ["-DCMAKE_C_FLAGS_RELEASE=-DNDEBUG", "-DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG", "-DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/websocketpp/HEAD-378437a", "-DCMAKE_BUILD_TYPE=Rele
Last 15 lines from /Users/lanjiedediannao/Library/Logs/Homebrew/websocketpp/01.HEAD-378437a",:
2018-05-24 17:34:07 +0800

cmake  . ["-DCMAKE_C_FLAGS_RELEASE=-DNDEBUG", "-DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG", "-DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/websocketpp/HEAD-378437a", "-DCMAKE_BUILD_TYPE=Release", "-DCMAKE_FIND_FRAMEWORK=LAST", "-DCMAKE_VERBOSE_MAKEFILE=ON", "-Wno-dev"]

CMake Error: The source directory "/tmp/websocketpp-20180524-26535-1ap1r7z/[-DCMAKE_C_FLAGS_RELEASE=-DNDEBUG," does not exist.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by rideoff** [comment]
==> Installing websocketpp from david-icracked/websocketpp
==> Cloning git://github.com/zaphoyd/websocketpp
Updating /Users/lanjiedediannao/Library/Caches/Homebrew/websocketpp--git
==> Checking out branch master
==> cmake  . ["-DCMAKE_C_FLAGS_RELEASE=-DNDEBUG", "-DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG", "-DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/websocketpp/HEAD-378437a", "-DCMAKE_BUILD_TYPE=Rele
Last 15 lines from /Users/lanjiedediannao/Library/Logs/Homebrew/websocketpp/01.HEAD-378437a",:
2018-05-24 17:34:07 +0800

cmake  . ["-DCMAKE_C_FLAGS_RELEASE=-DNDEBUG", "-DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG", "-DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/websocketpp/HEAD-378437a", "-DCMAKE_BUILD_TYPE=Release", "-DCMAKE_FIND_FRAMEWORK=LAST", "-DCMAKE_VERBOSE_MAKEFILE=ON", "-Wno-dev"]

CMake Error: The source directory "/tmp/websocketpp-20180524-26535-1ap1r7z/[-DCMAKE_C_FLAGS_RELEASE=-DNDEBUG," does not exist.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by merrymercy** [comment]
cc @Kipsora

**Comment by Kipsora** [comment]
This problem is caused by the outdated brew formula. You can fixed it either by manually installing `websocketpp` from source or modifying the formula file `/usr/local/Homebrew/Library/Taps/david-icracked/homebrew-websocketpp/websocketpp.rb` to the code below:
```ruby
require 'formula'

class Websocketpp < Formula
  head 'https://github.com/zaphoyd/websocketpp.git'

  depends_on 'cmake' => :build

  def install
    system "cmake  . #{std_cmake_args.join(" ")}"
    system "make install"
  end
end
```
Then you re-run the `brew install --HEAD david-icracked/websocketpp/websocketpp` command and you can successfully install `websocket` on your MAC.

**Comment by sven941112** [comment]
OSError: dlopen(/Users/pipi/Desktop/MAgent-master/magent/../../build/libmagent.dylib, 10): image not found.

How can I solve it?

**Comment by Kipsora** [comment]
@sven941112 Please create another issue so that the others can see your problem as well.

**Comment by sven941112** [comment]
I am running MAgent on my MacBook Pro m1, but some mistakes happened, which are listed as follows:
"OSError: dlopen(/Users/pipi/miniforge3/envs/py38/lib/python3.8/site-packages/magent/libmagent.dylib, 10): no suitable image found.  Did find:
	/Users/.../miniforge3/envs/py38/lib/python3.8/site-packages/magent/libmagent.dylib: mach-o, but wrong architecture
	/Users/.../miniforge3/envs/py38/lib/python3.8/site-packages/magent/libmagent.dylib: mach-o, but wrong architecture"
I don't know whether is my PC is based on ARM architecture. if yes, how can I solve it?
