### ISSUE TITLE
cannot find a blank position in a filled map

### ISSUE THREAD

**Issue by ddhostallero** [geek-ai/MAgent#18]
While I was running some simulation, this happened. I cannot replicate it since it happened only one. However, you might want to investigate it

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  /home/MAgent/src/gridworld/Map.cc:60 : cannot find a blank position in a filled map
```

**Comment by merrymercy** [comment]
This error means your map is full, so the engine cannot insert new object (agent or wall) into the map.
Do you add new agents during your simulation?

**Comment by petwill** [comment]
Is it okay to add new agents during simulation?

**Comment by merrymercy** [comment]
Yes, it is supported.
