### ISSUE TITLE
How do I render ?

### ISSUE THREAD

**Issue by arbaazkhan2** [geek-ai/MAgent#19]
env.render() doesn't do anything. Am I missing something?

**Comment by Kipsora** [comment]
Different from OpenAI gym, ```env.render()``` is just used to generate video files. To see the video in a render, please refer to the docs [here](https://github.com/geek-ai/MAgent/blob/master/doc/get_started.md#watch-video).

**Comment by nav74neet** [comment]
no module named 'magent'  how do i fix this?

**Comment by Kipsora** [comment]
@nav74neet Please reopen another issue due to no explicit relation to the topic of this issue.

**Comment by KornbergFresnel** [comment]
@nav74neet Hi, you can get instruction from: https://github.com/geek-ai/MAgent/issues/29
