### ISSUE TITLE
Invalid handle of the map data file

### ISSUE THREAD

**Issue by petwill** [geek-ai/MAgent#21]
When I typed in config.json and video_100.txt, it says 
magent::render::RenderException "Invalid handle of the map data file"
the file video_100.txt is in the directory build/render
Any ideas what may the problem be?

**Comment by petwill** [comment]
I just ran train_gathering.py, build build.sh on Arch linux

**Comment by petwill** [comment]
Found the solution.
The config.json in build/render was only for api_demo.
Had to write my own config for different games

**Comment by navallo** [comment]
Same problem.
Solved by cd to build/render first then execute ./render
