### ISSUE TITLE
Is there a way to save rendering result as video file(ex: .mp4)?

### ISSUE THREAD

**Issue by petwill** [geek-ai/MAgent#24]
Of course I can use something like selenium and save screenshots to form a video later.
But is there any easier or better way of doing this?

**Comment by Kipsora** [comment]
Currently, our render has not provided a way to save a standalone version of videos like MP4, MPEG and AVI. We have a very big map with millions of agents so basically we cannot save all of them into one video. But we might add some utilities to save the rendered episode in a clipped window.

**Comment by petwill** [comment]
![image](https://user-images.githubusercontent.com/16130918/40883886-ec31b650-6739-11e8-9f67-8565e7fc3aff.png)

How can I change  the parameters in "window" programatically?

**Comment by petwill** [comment]
I am just wondering how is the gif that are used to demo created?
I would like to do the same thing with my self-designed game.
Thanks in advance !

**Comment by Kipsora** [comment]
Currently the properties of window can be only modified by pressing Up, Down, Left and Right (see [here](https://github.com/geek-ai/MAgent/blob/master/doc/get_started.md#watch-video)). If you want to change it in a program, you may send the respective keys to the browser (but currently the render is only for the purpose of watching how agents perform).

**Comment by Kipsora** [comment]
The video in the README is firstly recorded by screen recording programs like Vokoscreen and then converted into GIF format using ffmpeg.

**Comment by petwill** [comment]
Thanks a lot!
