### ISSUE TITLE
Mode that agents cannot penetrate each other?

### ISSUE THREAD

**Issue by petwill** [geek-ai/MAgent#25]
Is there any support for environments where agents **cannot** go through each other?

For example, 
in the following scenario, even if agent a has a moving speed of 2, it still cannot move away.
```
 b
bab
 b
```

**Comment by merrymercy** [comment]
Sorry, there is no such mode.

You need to modify it by yourself. The related code is 
https://github.com/geek-ai/MAgent/blob/872680a8b9fee02c527306e65c4aeee1641b11a5/src/gridworld/GridWorld.cc#L573-L577

**Comment by petwill** [comment]
OK. Thanks
