### ISSUE TITLE
ModuleNotFoundError: No module named 'magent'

### ISSUE THREAD

**Issue by Downloadmarktown** [geek-ai/MAgent#26]
ModuleNotFoundError: No module named 'magent'

no module named 'magent' how do i fix this?

**Comment by Air-Fighter** [comment]
you should add the subdirectory  'python' of the project to the $PYTHONPATH

**Comment by Downloadmarktown** [comment]
thank you. I've already fixed this problem.

**Comment by Kipsora** [comment]
Closed due to being resolved.
