### ISSUE TITLE
ubutun16.04安装问题

### ISSUE THREAD

**Issue by wenshiwei** [geek-ai/MAgent#29]
是不是每次开机后再运行都需要重新安装或source一下？因为第一个例子跑过之后，第二个就会提示无法找到“”magent”

**Comment by KornbergFresnel** [comment]
@wenshiwei Hi, there are some instructions for your concern

1. write this in your `~/.bashrc` or `~/.zshrc`

`export PYTHONPATH=${PYTHONPATH}:./python`

then run `source ~/.zshrc` or `source ~/.bashrc` in your terminal

2. there is no need to run `source` again after you rebooted the machine

3. if you open several tabs in your terminal window, and run `source` in the one of them, so it is obviously that you cannot execute successfully in the other sub-windows. And the best way to active is restart (relaunch) your terminal !
