### ISSUE TITLE
where are the  video and the model of the example saved?

### ISSUE THREAD

**Issue by wenshiwei** [geek-ai/MAgent#30]
How watch to the result of example?For the pursuit ,gathering and battle.And that result where is it saved?

**Comment by KornbergFresnel** [comment]
@wenshiwei Hi, I'm sorry for that we have not created wiki yet, you can create your own running script with following the examples under the `examples/`. And if you have ever read about one of them, you will find the key is:

```python
# init the directory for render
env.set_render_dir("build/render")

# something .....

# render
env.render()
```

In the above code segment, that the result of render will be stored in `build/render`, more information please read: https://github.com/geek-ai/MAgent/blob/872680a8b9fee02c527306e65c4aeee1641b11a5/python/magent/gridworld.py#L427
