### ISSUE TITLE
Some questions about the action label

### ISSUE THREAD

**Issue by woaipichuli** [geek-ai/MAgent#36]
I have read the code and have some questions about the action label. In the doc file (get_start.md) you have provided,  there are 23 different actions agents can take. However, I have no idea about how to map the action label to a specific action (left or right,1 step or 2 step,etc). I would be appreciate if you can provide more details.

**Comment by merrymercy** [comment]
The mapping for that picture is 

![screenshot from 2018-08-08 15-02-39](https://user-images.githubusercontent.com/15100009/43866885-27a201ca-9b1c-11e8-82e3-6c7fbafd115c.png)

For different game config, the range of moving and attacking is different.
The turn actions are disabled by default.

**Comment by woaipichuli** [comment]
@merrymercy Thank you, that will be helpfull. Yes, watch the video can help, but that will needs lots of try. Does the mapping rules (from right to left, from top to bottom) of actions as shown in the figure are the same even when the game config changes?
