### ISSUE TITLE
ImportError: No module named 'base_renderer'

### ISSUE THREAD

**Issue by liuminggao** [geek-ai/MAgent#4]
run `show_battle_game.py` error

```
Traceback (most recent call last):
  File "examples/show_battle_game.py", line 9, in <module>
    from magent.renderer import PyGameRenderer
  File "/home/minghigh/Desktop/MAgent/python/magent/renderer/__init__.py", line 1, in <module>
    from base_renderer import BaseRenderer
ImportError: No module named 'base_renderer'
```

my **PYTHONPATH** is okey.

![screenshot from 2017-12-06 15-46-57](https://user-images.githubusercontent.com/32049996/33650460-0fb0a372-da9d-11e7-89a9-daf5d03de23a.png)

**Comment by Kipsora** [comment]
Thanks for submitting issues. We have fixed this bug (for python3).
