### ISSUE TITLE
libwebsocketpp-dev 未发现软件包

### ISSUE THREAD

**Issue by yinyanting** [geek-ai/MAgent#43]
XXXX-virtual-machine:~/MAgent-master$ sudo apt-get install cmake libwebsocketpp-dev
正在读取软件包列表... 完成
正在分析软件包的依赖关系树
正在读取状态信息... 完成
E: 未发现软件包 libwebsocketpp-dev
前两个软件包没有问题 ，但是libwebsocketpp-dev显示未发现，应该如何解决。

**Comment by petwill** [comment]
I guess you are using Ubuntu 14.04

**Comment by petwill** [comment]
I solved it by following similar methods mentioned here:
https://makandracards.com/makandra/47558-how-to-install-packages-from-newer-ubuntu-releases

**Comment by Kipsora** [comment]
Issue closed and if you have further questions or issues please reopen it or create a new issue.
