### ISSUE TITLE
how to use 'parameter-sharing DQN' in my own task?

### ISSUE THREAD

**Issue by OwalnutO** [geek-ai/MAgent#46]
Thanks for your brilliant code.

I want to know how can I use the RL algorithm in my onw task? For example , If I have my own environment to provide reward and many agents, how can I use your RL code to train on my dataset? In other words, I just want to know what is 'parameter-sharing DQN' and which part of the code I can use to train my own dataset?

**Comment by Kipsora** [comment]
The parameter-sharing DQN is targeting on optimizing the Environment defined [here](https://github.com/geek-ai/MAgent/blob/master/python/magent/environment.py), you can create your own class which inherits from it. However, the builtin model in MAgent is specialized so it is not recommended to directly apply the builtin model into your own environment. A better way to do this is just read through these codes and implement yourself.
