### ISSUE TITLE
Questions about the Observation 

### ISSUE THREAD

**Issue by GuiyangLuo** [geek-ai/MAgent#53]
Spatial view consists of several rectangular channels, Walls, group 1, group 1's hp, group 1's minimap, group 2, group 2's hp, group 2's minimap. I have following questions:

1. What's the meaning of hp?
2. What are included in the minimap? It contains the walls?
3. All these values should be o or 1. However, when I print some observation (Spatial view) out, it has other values like 1.667. I am very confused.

I really appreciate that if you can replay to it at your appropriate time.

**Comment by merrymercy** [comment]
I updated the description
https://github.com/geek-ai/MAgent/commit/d00c3b775d88950f58b8a8223ceae46929723164

Could this answer your questions?

**Comment by GuiyangLuo** [comment]
Thanks for your reply.  The updated description is very clear.
