### ISSUE TITLE
Does the built in model supports PyTorch?

### ISSUE THREAD

**Issue by lihuiknight** [geek-ai/MAgent#58]
I am learning how to use the magent toolkit. Below, i list some questions:

1.  It seems that PyTorch is much more friendly and efficient than tensorflow, especially in research community.  does the builtin model support pytorch?

2. How to run train_battle_game.py in my own pc without gpu despite it's expected it's time consuming to train large battle game? change map_size from 125 to 16? Actually, I only want to learn how to use this key APIs and embed this toolkit with my own project. Does any tutorial to introduce the key APIs?

**Comment by merrymercy** [comment]
1. This project is not active now. But we welcome you or other people’s contribution on pytorch support 
2. Yes you can try a small map_size.
