### ISSUE TITLE
Errors generated in bash build.sh in macOS

### ISSUE THREAD

**Issue by znnby1997** [geek-ai/MAgent#66]
`operator==(
^
/usr/local/include/boost/smart_ptr/shared_ptr.hpp:823:40: note: candidate
      template ignored: could not match 'shared_ptr' against 'reference_wrapper'
template<class T, class U> inline bool operator==(shared_ptr<T> const & ...
                                       ^
/usr/local/include/boost/smart_ptr/shared_ptr.hpp:846:31: note: candidate
      template ignored: could not match 'shared_ptr' against 'reference_wrapper'
template<class T> inline bool operator==( shared_ptr<T> const & p, boost...
                              ^
/usr/local/include/boost/smart_ptr/shared_ptr.hpp:851:31: note: candidate
      template ignored: could not match 'shared_ptr' against 'reference_wrapper'
template<class T> inline bool operator==( boost::detail::sp_nullptr_t, s...
                              ^
/usr/local/opt/llvm/bin/../include/c++/v1/array:371:1: note: candidate template
      ignored: could not match 'array' against 'reference_wrapper'
operator==(const array<_Tp, _Size>& __x, const array<_Tp, _Size>& __y)
^
/usr/local/opt/llvm/bin/../include/c++/v1/queue:362:1: note: candidate template
      ignored: could not match 'queue' against 'reference_wrapper'
operator==(const queue<_Tp, _Container>& __x,const queue<_Tp, _Container>& __y)
^
7 errors generated.
make[2]: *** [CMakeFiles/render.dir/src/render/backend/render.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
7 errors generated.
make[2]: *** [CMakeFiles/render.dir/src/render/backend/websocket.cc.o] Error 1
make[1]: *** [CMakeFiles/render.dir/all] Error 2
make: *** [all] Error 2`
All of errors are that could not match ... against 'reference_wrapper'

**Comment by Kipsora** [comment]
Please install boost@1.55 instead.
```bash
brew uninstall boost
brew install boost@1.55
brew link --force boost@1.55
```
