### ISSUE TITLE
Models for other exampes

### ISSUE THREAD

**Issue by MarkusMontenegro** [geek-ai/MAgent#69]
Hi there,
Im currently working on my master thesis, which is about improving the behavior of agents by using model checking. The Situation I have chosen as example is quite similar to the example "train_gather". 
Is it possible to get access to the model you have used for your demo video?
And how long did it take to train this model?

**Comment by Kipsora** [comment]
We do not have our trained model released yet but you can train it yourself by executing the script at `examples/train_gather.py`.
