### ISSUE TITLE
Can i get the position of the agent in gridworld?

### ISSUE THREAD

**Issue by lml519** [geek-ai/MAgent#71]
Can i get the position of the agent in gridworld? For example, I want to get the a predator's position in two dimension tuple.

**Comment by ZhaoMingYang-tju** [comment]
hello, do you resolve this problem? please tell me, thank you..

**Comment by lml519** [comment]
> 
> 
> hello, do you resolve this problem? please tell me, thank you..

Im so sorry to tell u this problem has not been solved. I will be appreciate if u can give me a hand.

**Comment by merrymercy** [comment]
https://github.com/geek-ai/MAgent/blob/84f0dd090fc7cabaf264eaeda961e4176bc003d7/python/magent/gridworld.py#L361
