### ISSUE TITLE
conflicting actions

### ISSUE THREAD

**Issue by MarkusMontenegro** [geek-ai/MAgent#74]
Hi,
What is the handling of conflicting actions?
For example, if there are 2 agents with 1 space between them, what happens if they decide in the same round to walk on this field?
Is the action canceled for both of them in this round or is just one of them getting the action?
I'm experiencing some kinds of deadlocks, where some agents have the same rewarding option, but instead of doing it, they do nothing and wait until the other agents with this option are gone to do it. Are their actions canceled because of the conflict?

**Comment by merrymercy** [comment]
If there are conflicting actions, one random agent will have the higher priority. Then the action of another agent will be canceled.

**Comment by MarkusMontenegro** [comment]
Is it possible to change thsi behavior, so that the agent with the lowest id always has the highest priority?
